// pages/my/my.js
const app = getApp()
Page({
  data:{
    
    nav:[{
      title:'工作台',
      subList:[{
        name:'系统通知',
        link:'',
        cover:'https://qizhifan.oss-cn-hangzhou.aliyuncs.com/yoga/system/venue/20220113/administration_icon_news.png',
        width:'52rpx',
        height:'52rpx'
      },{
        name:'扫码签到',
        link:'/pages/qrSign/index',
        cover:'https://qizhifan.oss-cn-hangzhou.aliyuncs.com/yoga/system/venue/20220113/administration_icon_scan.png',
        width:'52rpx',
        height:'52rpx'
      },{
        name:'请假管理',
        link:'/pages/my/vacate',
        cover:'https://qizhifan.oss-cn-hangzhou.aliyuncs.com/yoga/system/venue/20220113/administration_icon_leave.png',
        width:'52rpx',
        height:'52rpx'
      },{
        name:'课程取消提醒',
        link:'/pages/my/courseCancleRemind',
        cover:'https://qizhifan.oss-cn-hangzhou.aliyuncs.com/yoga/system/venue/20220113/administration_icon_cancel.png',
        width:'52rpx',
        height:'52rpx'
      },{
        name:'课程评价',
        link:'/pages/comment/index',
        cover:'https://qizhifan.oss-cn-hangzhou.aliyuncs.com/yoga/system/venue/20220113/administration_icon_appraise.png',
        width:'52rpx',
        height:'52rpx'
      },{
        name:'积分',
        link:'/pages/integral/integralSet',
        cover:'https://qizhifan.oss-cn-hangzhou.aliyuncs.com/yoga/system/venue/20220113/administration_icon_integral.png',
        width:'52rpx',
        height:'52rpx'
      },{
        name:'提现',
        link:'/pages/withdrawal/detail',
        cover:'https://qizhifan.oss-cn-hangzhou.aliyuncs.com/yoga/system/venue/20220113/administration_icon_withdraw.png',
        width:'52rpx',
        height:'52rpx'
      },{
        name:'帮助中心',
        link:'/pages/helpCenter/index',
        cover:'https://qizhifan.oss-cn-hangzhou.aliyuncs.com/yoga/images/20220308/c6204632fbe5dba15405a55a9e5b5414.png',
        width:'52rpx',
        height:'52rpx'
      },{
        name:'公告管理',
        link:'/pages/baseConfig/noticeManagerList',
        cover:'https://qizhifan.oss-cn-hangzhou.aliyuncs.com/yoga/images/20220311/540626253acd1d64980bb3c9df79ee4c.png',
        width:'52rpx',
        height:'52rpx'
      }]
      },{
      title:'待办事项',
      subList:[{
        name:'生日会员',
        link:'/pages/my/commonList?type=1',
        cover:'https://qizhifan.oss-cn-hangzhou.aliyuncs.com/yoga/system/venue/20220113/administration_icon_birthday.png',
        width:'52rpx',
        height:'52rpx'
      },{
        name:'不活跃会员',
        link:'/pages/my/commonList?type=4',
        cover:'https://qizhifan.oss-cn-hangzhou.aliyuncs.com/yoga/system/venue/20220113/administration_icon_inactive.png',
        width:'52rpx',
        height:'52rpx'
      },{
        name:'次数卡不足',
        link:'/pages/my/commonList?type=2',
        cover:'https://qizhifan.oss-cn-hangzhou.aliyuncs.com/yoga/system/venue/20220113/administration_icon_notimes.png',
        width:'52rpx',
        height:'52rpx'
      },{
        name:'储值卡不足',
        link:'/pages/my/commonList?type=3',
        cover:'https://qizhifan.oss-cn-hangzhou.aliyuncs.com/yoga/system/venue/20220113/administration_icon_insufficient.png',
        width:'52rpx',
        height:'52rpx'
      },{
        name:'即将到期会员',
        link:'/pages/my/commonList?type=5',
        cover:'https://qizhifan.oss-cn-hangzhou.aliyuncs.com/yoga/system/venue/20220113/administration_icon_expire.png',
        width:'52rpx',
        height:'52rpx'
      }]
    },{
      title:'营销工具',
      subList:[{
        name:'助力登顶',
        link:'/pages/activity/list?type=1',
        cover:'https://qizhifan.oss-cn-hangzhou.aliyuncs.com/yoga/system/venue/20220113/administration_icon_assistance.png',
        width:'52rpx',
        height:'52rpx'
      },{
        name:'限时秒杀',
        link:'/pages/activity/list?type=2',
        cover:'https://qizhifan.oss-cn-hangzhou.aliyuncs.com/yoga/system/venue/20220113/administration_icon_seckill.png',
        width:'52rpx',
        height:'52rpx'
      },{
        name:'幸运转盘',
        link:'/pages/activity/drawList?type=4',
        cover:'https://qizhifan.oss-cn-hangzhou.aliyuncs.com/yoga/system/venue/20220113/administration_icon_turntable.png',
        width:'52rpx',
        height:'52rpx'
      },{
        name:'超值拼团',
        link:'/pages/activity/list?type=3',
        cover:'https://qizhifan.oss-cn-hangzhou.aliyuncs.com/yoga/system/venue/20220113/administration_icon_Collage.png',
        width:'52rpx',
        height:'52rpx'
      }]
    }],
    iPhonex:false
  },
  onLoad(){
    this.setData({
      iPhonex:app.globalData.isIphoneX || false
    })
  },
  goToPage(e){
    const { link } = e.currentTarget.dataset
    console.log({link})
    if(!link){
      wx.showModal({
        title:'提示',
        content:'暂未开放',
        showCancel:false
      })
      return
    }
    wx.navigateTo({
      url: link,
    })
  }
})