let positionData = {
    girl: {
        chest:{
            top:'22',
            left:'23.5',
            width:'100',
            height:'100'
        },
        waist:{
            top:'29',
            left:'28.8',
            width:'84',
            height:'84'
        },
        hip:{
            top:'37',
            left:'14.8',
            width:'136',
            height:'136'
        },
        upper_arm_left:{
            top:'24',
            left:'4',
            width:'44',
            height:'44'
        },
        upper_arm_right:{
            top:'24',
            left:'73',
            width:'44',
            height:'44'
        },
        lower_arm_left:{
            top:'44',
            left:'-4',
            width:'40',
            height:'40'
        },
        lower_arm_right:{
            top:'44',
            left:'84',
            width:'40',
            height:'40'
        },
        big_leg_left:{
            top:'46',
            left:'17',
            width:'66',
            height:'66'
        },
        big_leg_right:{
            top:'46',
            left:'50',
            width:'66',
            height:'66'
        },
        small_leg_left:{
            top:'81',
            left:'28.8',
            width:'40',
            height:'40'
        },
        small_leg_right:{
            top:'81',
            left:'53',
            width:'40',
            height:'40'
        }
    },
    boy: {
        chest:{
            top:'24',
            left:'20',
            width:'144',
            height:'144'
        },
        waist:{
            top:'30',
            left:'22',
            width:'130',
            height:'130'
        },
        hip:{
            top:'38',
            left:'16',
            width:'160',
            height:'160'
        },
        upper_arm_left:{
            top:'26',
            left:'-3',
            width:'60',
            height:'60'
        },
        upper_arm_right:{
            top:'26',
            left:'77',
            width:'60',
            height:'60'
        },
        lower_arm_left:{
            top:'44',
            left:'-3',
            width:'48',
            height:'48'
        },
        lower_arm_right:{
            top:'44',
            left:'82',
            width:'48',
            height:'48'
        },
        big_leg_left:{
            top:'52',
            left:'17',
            width:'76',
            height:'76'
        },
        big_leg_right:{
            top:'52',
            left:'50',
            width:'76',
            height:'76'
        },
        small_leg_left:{
            top:'82',
            left:'23',
            width:'52',
            height:'52'
        },
        small_leg_right:{
            top:'82',
            left:'55',
            width:'52',
            height:'52'
        }
    }
}

let showData = [{
    name:'身高',
    key:'height',
    type:1,//1不变2上升3下降
    changeValue:0,
    unit:'cm',
    value:[],
  },{
    name:'体重',
    key:'weight',
    type:1,//1不变2上升3下降
    changeValue:0,
    unit:'kg',
    value:[]
  },{
    name:'BMI',
    key:'bmi',
    type:1,//1不变2上升3下降
    changeValue:0,
    unit:'kg/m^2',
    value:[]
  },{
    name:'体脂',
    key:'body_fat',
    type:1,//1不变2上升3下降
    changeValue:0,
    unit:'%',
    value:[]
  },{
    name:'上臂围（左）',
    key:'upper_arm_left',
    type:1,//1不变2上升3下降
    changeValue:0,
    unit:'cm',
    value:[]
  },{
    name:'上臂围（右）',
    key:'upper_arm_right',
    type:1,//1不变2上升3下降
    changeValue:0,
    unit:'cm',
    value:[]
  },{
    name:'下臂围（左）',
    key:'lower_arm_left',
    type:1,//1不变2上升3下降
    changeValue:0,
    unit:'cm',
    value:[]
  },{
    name:'下臂围（右）',
    key:'lower_arm_right',
    type:1,//1不变2上升3下降
    changeValue:0,
    unit:'cm',
    value:[]
  },{
    name:'胸围',
    key:'chest',
    type:1,//1不变2上升3下降
    changeValue:0,
    unit:'cm',
    value:[]
  },{
    name:'腰围',
    key:'waist',
    type:1,//1不变2上升3下降
    changeValue:0,
    unit:'cm',
    value:[]
  },{
    name:'臀围',
    key:'hip',
    type:1,//1不变2上升3下降
    changeValue:0,
    unit:'cm',
    value:[]
  },{
    name:'大腿围（左）',
    key:'big_leg_left',
    type:1,//1不变2上升3下降
    changeValue:0,
    unit:'cm',
    value:[]
  },{
    name:'大腿围（右）',
    key:'big_leg_right',
    type:1,//1不变2上升3下降
    changeValue:0,
    unit:'cm',
    value:[]
  },{
    name:'小腿围（左）',
    key:'small_leg_left',
    type:1,//1不变2上升3下降
    changeValue:0,
    unit:'cm',
    value:[]
  },{
    name:'小腿围（右）',
    key:'small_leg_right',
    type:1,//1不变2上升3下降
    changeValue:0,
    unit:'cm',
    value:[]
  }]

export {
    positionData,
    showData
}