let positionData = {
    girl: {
        chest:{
            top:'22',
            left:'23.5',
            width:'100',
            height:'100'
        },
        waist:{
            top:'29',
            left:'28.8',
            width:'84',
            height:'84'
        },
        hip:{
            top:'37',
            left:'14.8',
            width:'136',
            height:'136'
        },
        upper_arm_left:{
            top:'24',
            left:'4',
            width:'44',
            height:'44'
        },
        upper_arm_right:{
            top:'24',
            left:'73',
            width:'44',
            height:'44'
        },
        lower_arm_left:{
            top:'44',
            left:'-4',
            width:'40',
            height:'40'
        },
        lower_arm_right:{
            top:'44',
            left:'84',
            width:'40',
            height:'40'
        },
        big_leg_left:{
            top:'46',
            left:'17',
            width:'66',
            height:'66'
        },
        big_leg_right:{
            top:'46',
            left:'50',
            width:'66',
            height:'66'
        },
        small_leg_left:{
            top:'81',
            left:'28.8',
            width:'40',
            height:'40'
        },
        small_leg_right:{
            top:'81',
            left:'53',
            width:'40',
            height:'40'
        }
    },
    boy: {
        chest:{
            top:'24',
            left:'20',
            width:'144',
            height:'144'
        },
        waist:{
            top:'30',
            left:'22',
            width:'130',
            height:'130'
        },
        hip:{
            top:'38',
            left:'16',
            width:'160',
            height:'160'
        },
        upper_arm_left:{
            top:'26',
            left:'-3',
            width:'60',
            height:'60'
        },
        upper_arm_right:{
            top:'26',
            left:'77',
            width:'60',
            height:'60'
        },
        lower_arm_left:{
            top:'44',
            left:'-3',
            width:'48',
            height:'48'
        },
        lower_arm_right:{
            top:'44',
            left:'82',
            width:'48',
            height:'48'
        },
        big_leg_left:{
            top:'52',
            left:'17',
            width:'76',
            height:'76'
        },
        big_leg_right:{
            top:'52',
            left:'50',
            width:'76',
            height:'76'
        },
        small_leg_left:{
            top:'82',
            left:'23',
            width:'52',
            height:'52'
        },
        small_leg_right:{
            top:'82',
            left:'55',
            width:'52',
            height:'52'
        }
    }
}

export {
    positionData
}